Задание 2.1
seeuagony/TKI-142 pull request #12
Opened 2024-10-07 09:36 UTC by seeuagony

Код для решения задания 2.1 #10

2024-10-21 12:29 UTC, MarinaPaley requested changes
не исправили

2024-10-21 12:29 UTC, MarinaPaley commented on Task 1/Task 1/Task1.c
>  }
`return 0;`

2024-10-21 12:45 UTC, seeuagony commented
> не исправили

Вы смотрите не тот файл 😓 Задание в Task2.1.c. Файл случайно сюда попал

2024-10-21 17:43 UTC, BalakinaEP requested changes

2024-10-21 17:43 UTC, BalakinaEP commented on Tasks 2/Tasks 2/Task2.1.c
> +    printf("Select the type of operation: \n1 - Calculate the number of negative numbers\n2 - Calculate the absolute sum\n");
не исправили

2024-10-21 17:43 UTC, BalakinaEP commented on Tasks 2/Tasks 2/Task2.1.c
> +    if (check != 1 && check != 2) {
не исправили

2024-10-28 12:18 UTC, MarinaPaley requested changes

2024-10-28 12:18 UTC, MarinaPaley commented on Tasks 2/Tasks 2/Task2.1.c
> +    printf("Select the type of operation: \n1 - Calculate the number of negative numbers\n2 - Calculate the absolute sum\n");
` printf("Select the type of operation: \n%d - Calculate the number of negative numbers\n%d - Calculate the absolute sum\n", (int)getNegatives, (int)getAbsoluteSum);`

2024-11-20 12:06 UTC, MarinaPaley approved these changes

2024-11-20 16:26 UTC, merged