Решение задачи 2.2
seeuagony/TKI-142 pull request #14
Opened 2024-10-14 11:43 UTC by seeuagony

Код для решения задачи 2.2

2024-10-20 16:08 UTC, seeuagony commented on Tasks 2/Tasks 2/task2.2.c
> +#define PI 3.14159265358979323846
![image](https://github.com/user-attachments/assets/f9bfb8ef-3591-4b58-892e-86096db9adf7)

2024-10-21 13:53 UTC, MarinaPaley requested changes

2024-10-21 13:53 UTC, MarinaPaley commented on Tasks 2/Tasks 2/task2.2.c
> +#define M_PI 3.14159265358979323846
нет. Определена в math.h

2024-10-23 09:51 UTC, MarinaPaley commented on Tasks 2/Tasks 2/task2.2.c
> +    double value;
неинициализированная переменная

2024-10-23 09:51 UTC, MarinaPaley commented on Tasks 2/Tasks 2/task2.2.c
> +#define _USE_MATH_DEFINES
наверх

2024-10-28 12:19 UTC, MarinaPaley approved these changes

2024-11-11 08:53 UTC, closed without merging