Решение задачи
seeuagony/TKI-142 pull request #16
Opened 2024-10-20 20:43 UTC by seeuagony

Код для задания 2.3 #15

2024-10-21 14:14 UTC, MarinaPaley requested changes

2024-10-21 14:14 UTC, MarinaPaley commented on task2.3.c
> +int houseFits(const double siteHeight, const double siteWidth, const double fHouseHeight, const double fHouseWidth, const double sHouseHeight, const double sHouseWidth) {
bool

2024-10-23 09:09 UTC, BalakinaEP requested changes

2024-10-23 09:09 UTC, BalakinaEP commented on task2.3.c
> +double Input(void);
`double input(void);`
Везде одинаково

2024-10-23 09:09 UTC, BalakinaEP commented on task2.3.c
> +    }
нужно обсудить при встрече

2024-10-28 12:19 UTC, MarinaPaley approved these changes

2024-11-11 08:54 UTC, closed without merging