Код для решения 3.1
seeuagony/TKI-142 pull request #18
Opened 2024-10-28 11:29 UTC by seeuagony

Код для решения 3.1 #17

2024-10-28 12:16 UTC, MarinaPaley requested changes

2024-10-28 12:16 UTC, MarinaPaley commented on task3.1.c
> +double getY(double x);
const

2024-10-28 12:16 UTC, MarinaPaley commented on task3.1.c
> +	xCheck(value);
Убрать

2024-10-28 12:16 UTC, MarinaPaley commented on task3.1.c
> +    const double step = input();
Отдельная функция для шага с проверкой на положительность

2024-11-20 12:08 UTC, MarinaPaley requested changes

2024-11-20 12:08 UTC, MarinaPaley commented on task3.1.c
> +    return x < 1;
а тангенс?

2024-11-24 13:49 UTC, seeuagony commented on task3.1.c
> +    return x < 1;
добавил проверку тангенса

2024-11-27 13:42 UTC, MarinaPaley approved these changes

2024-11-28 19:45 UTC, merged