Решение 3.2
seeuagony/TKI-142 pull request #20
Opened 2024-11-16 18:59 UTC by seeuagony

Код для решения #19

2024-11-20 11:06 UTC, BalakinaEP requested changes

2024-11-20 11:06 UTC, BalakinaEP commented on 3.2.c
> +double getLessThanE(const int n, const double e);
n никак не используется в данном расчете

2024-11-20 11:06 UTC, BalakinaEP commented on 3.2.c
> +double nextTerm(double current, int a);
const

2024-11-20 11:06 UTC, BalakinaEP commented on 3.2.c
> +            break;
Это условие является окончанием цикла и должно быть в выше вместо k <= n, не учли DBL_EPSILON

2024-11-29 13:30 UTC, BalakinaEP requested changes

2024-11-29 13:30 UTC, BalakinaEP commented on 3.2.c
> +double nextTerm(double current, int k);
все параметры константы

2024-11-29 13:30 UTC, BalakinaEP commented on 3.2.c
> +    return sum;
потеряли первый член последовательности при расчете суммы

2024-11-29 13:30 UTC, BalakinaEP commented on 3.2.c
> +        k++;
Аналогично, потеряли первый член последовательности при расчете суммы

2024-12-02 14:39 UTC, MarinaPaley requested changes

2024-12-02 14:39 UTC, MarinaPaley commented on 3.2.c
> +        sum += currentTerm;
поменять и вернуть сумма = 0 (начальная)

2024-12-10 15:09 UTC, MarinaPaley approved these changes

2024-12-10 18:55 UTC, merged