Решение 4.1
seeuagony/TKI-142 pull request #28
Opened 2024-12-08 16:25 UTC by seeuagony

Код для решения 4.1 #27

2024-12-09 15:15 UTC, BalakinaEP commented on task4.1.c
> +    checkArr(copiedArr);
Зачем это? А вот arr перед копированием нужно бы было проверить

2024-12-09 15:16 UTC, BalakinaEP commented on task4.1.c
> +        if ((arr[i] > 0 && arr[i + 1] > 0) || (arr[i] < 0 && arr[i + 1] < 0)) {
(arr[i] * arr[i + 1] > 0 && arr[i] * arr[i + 1] < x)

2024-12-16 14:49 UTC, BalakinaEP requested changes

2024-12-16 14:49 UTC, BalakinaEP commented on task4.1.c
> +void reverseBetweenMinAndMax(int* arr, size_t n);
`
void reverseBetweenMinAndMax(int* arr, const size_t n);`

2024-12-23 09:16 UTC, Vadimololo19 approved these changes

2024-12-23 09:30 UTC, merged